### ISSUE TITLE
miner connected, but it doesn't receive jobs.

### ISSUE THREAD

**Issue by EternityTula** [eXtremal-ik7/pool_frontend_zcash#12]
Hi eXtremal! 

I've started a pool and can change minimal payout in the web interface, miner is connected, but it doesn't receive jobs. How can I identify the cause?

Thank you very much for the pool software.

**Comment by romanick** [comment]
I have a similar problem. The following messages are displayed in the pool output:
> can't check balance, no connection to wallet

poolrpccmd failed too:
$poolrpccmd/poolrpccmd p2p://10.10.4.184 getBlockTemplate
Error: connecting error

My zcash daemon is started with following params:

> zcashd -p2pport=12201 -bind=10.10.4.184

Pool starting (on 10.10.8.253) with cfg file:

```
pool_frontend_zcash {
  isMaster = "true";
  poolFee = "1";
  poolFeeAddr = "t1ZyMLPNUSijunUazfCKSgphyMMEiuM2VHH";
  walletAddrs = ["p2p://10.10.4.184:12201"];
  localAddress = "p2p://10.10.8.253:13301";
  walletAppName = "pool_rpc";
  poolAppName = "pool_frontend_zcash";
  requiredConfirmations = "10";
  defaultMinimalPayout = "0.01";
  dbPath = "/home/tester/pool.zcash";
  keepRoundTime = "3";
  keepStatsTime = "2";
  confirmationsCheckInterval = "7";
  payoutInterval = "30";
  balanceCheckInterval = "3";
  statisticCheckInterval = "1";

  zmqclientHost = "coinsforall.io";
  zmqclientListenPort = "6668";
  zmqclientWorkPort = "60200";

  pool_zaddr = "zcZgU5GogEoxcZhESkshG2YQNPBVRXVhqZP1Pb3Ux8pcndtUp9KMPbAXkbr2ehP1DW42UPEALAQSCGMEw6bVqprFve7Q2xo";
  pool_taddr = "t1ZyMLPNUSijunUazfCKSgphyMMEiuM2VHH";
}
```
miner starting with params:

> ./nheqminer -l 10.10.8.253:13301 -u t1dGyd2hroeewXau9szDmtgJwkudFCGhrZg -t 4 -d 0

**Comment by romanick** [comment]
Hi!
I have this bug too!

Used nhqeminer
./nheqminer -l 10.10.8.253:13301 -u t1dGyd2hroeewXau9szDmtgJwkudFCGhrZg -t 4 -d 0

**Comment by romanick** [comment]
I tried use xpmclient, but no result:

> user@user-desktop:~/soft/zcashclient-0.2.4$ ./zcashgpuclient
> madPrimeMiner-v1.1
> ClientName = 'test1'  ClientID = 4129959555  InstanceID = 3999553940
> Address = 't1dGyd2hroeewXau9szDmtgJwkudFCGhrZg'
> found platform[0] name = 'NVIDIA CUDA'
> <info> found 1 devices
> Using device 0 as GPU 0
> <info> OpenCL: alloc 196 bytes
> <info> OpenCL: alloc 117440512 bytes
> <info> OpenCL: alloc 117440512 bytes
> <info> OpenCL: alloc 524288 bytes
> <info> OpenCL: alloc 16384 bytes
> <info> OpenCL: alloc 4 bytes
> <info> OpenCL: alloc 196 bytes
> <info> OpenCL: alloc 117440512 bytes
> <info> OpenCL: alloc 117440512 bytes
> <info> OpenCL: alloc 524288 bytes
> <info> OpenCL: alloc 16384 bytes
> <info> OpenCL: alloc 4 bytes
> threads: 8192, work size: 256
> Connecting to frontend: 10.10.8.253:13301 ...
> ZCash GPU miner thread 0 started

Pool output:

> <info> clients: 0, workers: 0, cpus: 0, gpus: 0, asics: 0, other: 0, latency: 0, power: 0
> - new block signal: 11349, diff=61992102.81046, approximate shares per block: 7749042
> - new block signal: 11350, diff=63048766.18338, approximate shares per block: 7881125
> - new block signal: 11351, diff=63549832.87414, approximate shares per block: 7943759
>   <info> clients: 0, workers: 0, cpus: 0, gpus: 0, asics: 0, other: 0, latency: 0, power: 0
>   <info> accounting: balance=0.00 req/balance=0.00 req/queue=0.00 immature=0.00 users=0.00 queued=0.00, net=0.00
>   <info> clients: 0, workers: 0, cpus: 0, gpus: 0, asics: 0, other: 0, latency: 0, power: 0

**Comment by nginnever** [comment]
Also having an issue with optiminer saying `waiting for work from pool`

however Silentarmy seems to work just fine.

**Comment by romanick** [comment]
I resolved the problem. Why no place where specified valid port for miners? It's 3357!
Just connect to port 3357 - all work!

**Comment by nginnever** [comment]
The problem I was having with optminer not connect is because of this line https://github.com/eXtremal-ik7/pool_frontend_zcash/blob/master/src/stratum.cpp#L140

Optiminer only sends one argument it seems [0] = '/optimner/0.3.4/zcash

Sending the correct connection info in place of it missing from the miner arguments was my workaround.

**Comment by EternityTula** [comment]
romanick, thank you very much!
[createListener(base, 3357, stratumProc, 0, &context);](https://github.com/eXtremal-ik7/pool_frontend_zcash/blob/master/src/main.cpp#L618])
