### ISSUE TITLE
Stratum diff

### ISSUE THREAD

**Issue by scorpio18** [eXtremal-ik7/pool_frontend_zcash#18]
If i change the stratum diff from 0x00800 to 0x000f0800 is seems that the stats are way to off , what do i need to change so the stats to match

**Comment by CloudMiningPool** [comment]
In which file you have change startum diff ?
Thank you

**Comment by nginnever** [comment]
It's hardcoded in the stratum setTarget message here.

https://github.com/eXtremal-ik7/pool_frontend_zcash/blob/master/src/zcashpool.cpp#L519

**Comment by eXtremal-ik7** [comment]
Stratum diff moved to config, closed
