### ISSUE TITLE
poolcore compile error (another!)

### ISSUE THREAD

**Issue by blackice2013** [eXtremal-ik7/pool_frontend_zcash#22]
Hi,
I cant compile poolcore:
zcash@joanc-VirtualBox:~/poolcore/x86_64-Linux$ make -j5
[  5%] Building CXX object zcash/CMakeFiles/poolrpczcash.dir/zcash.cpp.o
[ 27%] Built target poolcommon
[ 38%] Built target poolrpccmd
[ 88%] Built target poolcore
In file included from /home/zcash/poolcore/src/zcash/zcash.cpp:3:0:
/home/zcash/zcash/src/main.h:10:35: fatal error: config/bitcoin-config.h: No existe el archivo o el directorio
compilation terminated.
zcash/CMakeFiles/poolrpczcash.dir/build.make:86: fallo en las instrucciones para el objetivo 'zcash/CMakeFiles/poolrpczcash.dir/zcash.cpp.o'
make[2]: *** [zcash/CMakeFiles/poolrpczcash.dir/zcash.cpp.o] Error 1
CMakeFiles/Makefile2:250: fallo en las instrucciones para el objetivo 'zcash/CMakeFiles/poolrpczcash.dir/all'
make[1]: *** [zcash/CMakeFiles/poolrpczcash.dir/all] Error 2
Makefile:83: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2

What can I do?
Thanks!

**Comment by zhoujianwei** [comment]
哥  你解决了没
