### ISSUE TITLE
cmake Errors

### ISSUE THREAD

**Issue by blackice2013** [eXtremal-ik7/pool_frontend_zcash#24]
Sry, but I am stuck now.
cant pass from cmake commands.
It throws me lots of errors: Exampe:

cd joanc/pool_frontend_zcash
mkdir x86_64-Linux
cd x86_64-Linux
cmake ../src -DROOT_SOURCE_DIR=/home/joanc/
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
AIO_INCLUDE_DIR
   used as include directory in directory /home/joanc/pool_frontend_zcash/src
   used as include directory in directory /home/joanc/pool_frontend_zcash/src
   used as include directory in directory /home/joanc/pool_frontend_zcash/src
AIO_LIBRARY
    linked by target "pool_frontend_zcash" in directory /home/joanc/pool_frontend_zcash/src
CONFIG4CPP_INCLUDE_DIR
   used as include directory in directory /home/joanc/pool_frontend_zcash/src
   used as include directory in directory /home/joanc/pool_frontend_zcash/src
   used as include directory in directory /home/joanc/pool_frontend_zcash/src
CONFIG4CPP_LIBRARY
    linked by target "pool_frontend_zcash" in directory /home/joanc/pool_frontend_zcash/src
P2PUTILS_LIBRARY
    linked by target "pool_frontend_zcash" in directory /home/joanc/pool_frontend_zcash/src
P2P_LIBRARY
    linked by target "pool_frontend_zcash" in directory /home/joanc/pool_frontend_zcash/src
POOLCOMMON_LIBRARY
    linked by target "pool_frontend_zcash" in directory /home/joanc/pool_frontend_zcash/src
POOLCORE_INCLUDE_DIR
   used as include directory in directory /home/joanc/pool_frontend_zcash/src
   used as include directory in directory /home/joanc/pool_frontend_zcash/src
   used as include directory in directory /home/joanc/pool_frontend_zcash/src
POOLCORE_LIBRARY
    linked by target "pool_frontend_zcash" in directory /home/joanc/pool_frontend_zcash/src

-- Configuring incomplete, errors occurred!
See also "/home/joanc/pool_frontend_zcash/x86_64-Linux/CMakeFiles/CMakeOutput.log".
See also "/home/joanc/pool_frontend_zcash/x86_64-Linux/CMakeFiles/CMakeError.log".

Getting same error with every almost every cmake I do :(
What I am doing wrong? missing something?
Thanks!

**Comment by innova-market** [comment]
cmake version 3.2.2
