### ISSUE TITLE
fatal error on make -j5

### ISSUE THREAD

**Issue by charlesrocket** [eXtremal-ik7/pool_frontend_zcash#31]
rocket@rkt-mbp:~/zec/poolcore/x86_64-Linux$ make -j5
[ 22%] Built target poolcommon
[ 27%] Building CXX object zcash/CMakeFiles/poolrpczcash.dir/zcash.cpp.o
[ 38%] Built target poolrpccmd
[ 88%] Built target poolcore
In file included from /home/rocket/zec/poolcore/src/zcash/zcash.cpp:3:0:
/home/rocket/zec/zcash/src/main.h:10:35: fatal error: config/bitcoin-config.h: No such file or directory
compilation terminated.
zcash/CMakeFiles/poolrpczcash.dir/build.make:86: recipe for target 'zcash/CMakeFiles/poolrpczcash.dir/zcash.cpp.o' failed
make[2]: *** [zcash/CMakeFiles/poolrpczcash.dir/zcash.cpp.o] Error 1
CMakeFiles/Makefile2:250: recipe for target 'zcash/CMakeFiles/poolrpczcash.dir/all' failed
make[1]: *** [zcash/CMakeFiles/poolrpczcash.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eXtremal-ik7** [comment]
Build zcash daemon with command ./zcutil/build.sh before 'poolcore' repository, use zcash 1.0.6 version.
