### ISSUE TITLE
How to make the work update at least once in 10 minutes?

### ISSUE THREAD

**Issue by EternityTula** [eXtremal-ik7/pool_frontend_zcash#32]
Pool distributes tasks to employees when it receives information about new block. When the next block is searched for more than 10 minutes, some miners believe that something is wrong and tries to reconnect. Please tell me how to make the work update at least once in 10 minutes.

Thank you very much for your product!
Excuse my English.

**Comment by eXtremal-ik7** [comment]
What miner you use?
Also you can use email from coinsforall site for Russian support.

**Comment by EternityTula** [comment]
Previously, it was a problem with the Claymore (v11.1: "ZEC:: No new jobs were received for 12 mins - something wrong with the pool, disconnect."). 
I was trying to rent Nicehash:
- If the unit is searched for more than 10 minutes - disables the order.
- For one connection gives no more than 15000 sol. And when you rent more - you get one worker for many connections. Solutions in the database increases, so that everything will be fine I think here. The truth is difficult to consider Nicehash cheating or not, but I hope that is not much)

**Comment by eXtremal-ik7** [comment]
> Previously, it was a problem with the Claymore (v11.1: "ZEC:: No new jobs were received for 12 mins - something wrong with the pool, disconnect.").
It's miner problem, you can use .bat or .sh script for restart.

For nicehash, I don't understand what it means "If the unit is searched for more than 10 minutes - disables the order."

**Comment by EternityTula** [comment]
Inactivity of equipment occurs.
There are no problems in restarting - the miner itself is reconnected after 20 seconds.

NisHash: When you buy a fixed capacity at an attractive price, the service ensures stability of the hash. If new tasks are not distributed 10 minutes - the service disconnects the miners from the pool. The order goes into the "dead" mode. From the balance write off compensation for the miners for reconnection. After 60 + - seconds, the service reconnects the miners. If the idle time in the "dead" mode exceeds 10% of the time of the order - the order is canceled as inefficient. The cost of fixed orders is constantly changing. Buy for an extended price is not often obtained. This is aggrieved by the periodic cancellation of orders.
By the way. On ZKlassik the pool started, blocks finds.
If you put a 0% pool commission and the wallet is empty: stumbles after the first attempt to transfer the funds, says "there is not enough tax".
When (and if :)) I go to "+" then I will thank you for the wonderful software product. All the best!

**Comment by eXtremal-ik7** [comment]
Ok, it really client problem, for workaround pool can resend work every 10 minutes.

> If you put a 0% pool commission and the wallet is empty: stumbles after the first attempt to transfer the funds, says "there is not enough tax".

Yes, you can't use immature coins, need wait a time.
