### ISSUE TITLE
support new version of zcash

### ISSUE THREAD

**Issue by adrianrobotka** [eXtremal-ik7/pool_frontend_zcash#42]
I was not able to build and setup pool_frontend_zcash with the latest zcash version.
I have used setup instructions from this repo and [forum.z.cash](https://forum.z.cash/t/set-up-your-own-private-stratum-pool/9043).
Is it possible to work with the new zcash (v1.1.2)?

**Comment by eXtremal-ik7** [comment]
it is possible, wait a patch for 1.1.2

**Comment by adrianrobotka** [comment]
Thanks. Sorry for the next question. I am a newbie here.
This patch is about zcash, poolcore or pool_frontend_zcash?
Approximately how long does it take to release a patch?

**Comment by eXtremal-ik7** [comment]
poolcore
https://github.com/eXtremal-ik7/poolcore/commit/94d7605ec969b00aff49aed547cd8aa80769c78c

**Comment by adrianrobotka** [comment]
Thanks, it works fine.
