### ISSUE TITLE
After patching pool.diff

### ISSUE THREAD

**Issue by burimaliu** [eXtremal-ik7/pool_frontend_zcash#5]
```
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `AppInit2(boost::thread_group&, CScheduler&)':
/root/setup/zcash/src/init.cpp:1522: undefined reference to `poolRpcThread(void*)'
collect2: error: ld returned 1 exit status
Makefile:3114: recipe for target 'zcashd' failed
make[2]: *** [zcashd] Error 1
make[2]: *** Waiting for unfinished jobs....
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `AppInit2(boost::thread_group&, CScheduler&)':
/root/setup/zcash/src/init.cpp:1522: undefined reference to `poolRpcThread(void*)'

```

Maybe its because i've checked out zcash 1.0.1 ?

**Comment by eXtremal-ik7** [comment]
Yes, need patch with pool.diff again

**Comment by burimaliu** [comment]
Actually that was not the case, i went ahead and modified lines on .cpp files to make it compile.

However i am not able to talk with wallet.

It says `Error: connecting error`

**Comment by burimaliu** [comment]
I am still having this issue when executing `poolrpccmd/poolrpccmd p2p://127.0.0.1:12201 getInfo` response is `Error: connecting error`

**Comment by eXtremal-ik7** [comment]
You build zcashd without patch (pool.diff), or launch it without -p2pport=12201 option

**Comment by burimaliu** [comment]
On zcash cloned directory i did `patch -p0 < pool_frontend_zcash/pool.diff` then on Makefile i replaced this: `LIBZCASH_LIBS = -lsnark -lgmp -lgmpxx -lboost_system-mt -lcrypto -lsodium -fopenmp`

with this: `LIBZCASH_LIBS = -lsnark -lgmp -lgmpxx -lboost_system-mt -lcrypto -lsodium -fopenmp -LYOUR_BUILD_DIRECTORY/poolcore/x86_64-Linux/zcash -lpoolrpczcash -LYOUR_BUILD_DIRECTORY/libp2p/x86_64-Linux/p2p -lp2p -LYOUR_BUILD_DIRECTORY/libp2p/x86_64-Linux/asyncio -lasyncio-0.3 -lrt`

and then ran again `make -j5` and then ran zcashd with  `-p2pport=12201`

So not sure what i've done wrong.

**Comment by nginnever** [comment]
Having the same exact issue. Were you able to solve this @burimaliu ?

**Comment by burimaliu** [comment]
@nginnever, i have solved it by updating Makefile on `zcash/src/` directory.
