### ISSUE TITLE
The instructions step by step for ubuntu server 16, for example?

### ISSUE THREAD

**Issue by vetal-com** [eXtremal-ik7/pool_frontend_zcash#6]
Hi!
Сan do for user ?

**Comment by eXtremal-ik7** [comment]
Already in readme.md file

**Comment by vetal-com** [comment]
In which file should I add these lines?

Add path to pool libraries in Makefile:

--- src/Makefile        2016-11-08 13:36:41.033699973 +0300
+++ src/Makefile        2016-11-08 13:37:20.889665298 +0300
@@ -1380,7 +1380,7 @@
 LIBSNARK_LIBS = -lsnark
 LIBTOOL = $(SHELL) $(top_builddir)/libtool
 LIBTOOL_APP_LDFLAGS = 
-LIBZCASH_LIBS = -lsnark -lgmp -lgmpxx -lboost_system-mt -lcrypto -lsodium -fopenmp
+LIBZCASH_LIBS = -lsnark -lgmp -lgmpxx -lboost_system-mt -lcrypto -lsodium -fopenmp -LYOUR_BUILD_DIRECTORY/poolcore/x86_64-Linux/zcash -lpoolrpczcash -LYOUR_BUILD_DIRECTORY/libp2p/x86_64-Linux/p2p -lp2p -LYOUR_BUILD_DIRECTORY/libp2p/x86_64-Linux/asyncio -lasyncio-0.3 -lrt
 LIPO = 
 LN_S = ln -s
 LRELEASE =
